version = "2.0"
watch_list = ["docs/index.md", "docs/contents.md", "notebooks/**/*.md"]

hooks = ["quarto_attributes"]

[markers]
open="^(?P<indent>\\s*)```(?P<properties>.*)$"
close="^(?P<indent>\\s*)```\\s*$"
